
What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started

### Tensors


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [8]:
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 1.4013e-44],
        [9.4591e-39, 2.0211e+21, 3.1672e-41],
        [1.5624e-42, 2.7624e-36, 0.0000e+00],
        [0.0000e+00, 1.4013e-44, 6.8523e-43],
        [2.0211e+21, 3.1672e-41, 3.3631e-44]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0639, 0.8350, 0.8137],
        [0.9438, 0.3267, 0.6345],
        [0.3221, 0.8072, 0.2450],
        [0.1611, 0.3046, 0.9591],
        [0.8094, 0.4070, 0.7709]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [11]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)
print(x.type())                               # result has the same size (default float is 32 bits)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9264,  0.9845, -1.4270],
        [ 0.5645, -0.1839,  0.6598],
        [-0.6687,  0.1758, -0.8071],
        [ 0.4930,  1.1076, -0.7585],
        [ 0.2252, -0.5155,  1.1213]])
torch.FloatTensor


Get its size:



In [14]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


**Note** `torch.shape` is in fact a tuple, so it supports all tuple operations.

## Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [15]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.7104,  1.4484, -0.5723],
        [ 1.5640, -0.0256,  1.0924],
        [-0.2140,  0.5445, -0.1556],
        [ 0.7056,  2.0569, -0.1510],
        [ 0.4343,  0.3889,  1.3247]])


Addition: syntax 2



In [16]:
print(torch.add(x, y))

tensor([[-0.7104,  1.4484, -0.5723],
        [ 1.5640, -0.0256,  1.0924],
        [-0.2140,  0.5445, -0.1556],
        [ 0.7056,  2.0569, -0.1510],
        [ 0.4343,  0.3889,  1.3247]])


Addition: providing an output tensor as argument



In [17]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.7104,  1.4484, -0.5723],
        [ 1.5640, -0.0256,  1.0924],
        [-0.2140,  0.5445, -0.1556],
        [ 0.7056,  2.0569, -0.1510],
        [ 0.4343,  0.3889,  1.3247]])


Addition: in-place



In [18]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.7104,  1.4484, -0.5723],
        [ 1.5640, -0.0256,  1.0924],
        [-0.2140,  0.5445, -0.1556],
        [ 0.7056,  2.0569, -0.1510],
        [ 0.4343,  0.3889,  1.3247]])


Since we are handling big data, it may become essential to avoid copying of big objects.

Any operation that mutates a tensor in-place is post-fixed with an **`_`**.

For example: **`x.copy_(y)`**, **`x.t_()`**, will change **`x`** in-place.

You can use standard NumPy-like indexing with all bells and whistles!



In [20]:
print(x[:, 1])

tensor([ 0.9845, -0.1839,  0.1758,  1.1076, -0.5155])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [21]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [13]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.3722])
1.3721507787704468


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  ([torch tensors](https://pytorch.org/docs/torch))

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will **share** their underlying memory
locations, and changing one will change the other.

## Converting a Torch Tensor to a NumPy Array



In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)
type(b)

[1. 1. 1. 1. 1.]


numpy.ndarray

See how the numpy array is changed when we modify the tensor in-place.



In [25]:
a.add_(1)
print(a)
print('numpy.ndarray',b)

tensor([3., 3., 3., 3., 3.])
numpy.ndarray [3. 3. 3. 3. 3.]


## Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [26]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back and forth.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.

For this on Collab you must select a Runtime->Change Runtime-> T4 GPU, if available.



In [19]:
x = torch.tensor([1.])
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
device="cpu"
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z,z.type())
    print(z.to("cpu", torch.double))        # ``.to`` can also change dtype together!

tensor([2.], device='cuda:0') torch.cuda.FloatTensor
tensor([2.], dtype=torch.float64)


### If you want to write device independent code

In [17]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x = x.to(device)  # this will go to GPU if available otherwise it doesn't change anything
device

device(type='cuda')

Check the following link for working with multiple GPUs

https://pytorch.org/docs/stable/notes/cuda.html#cuda-semantics

## Explicit cpu/cuda syntax

In [21]:
# Send a pyTorch tensor to GPU
if torch.cuda.is_available():

    # How many GPUs do we have?
    num_gpus    = torch.cuda.device_count()
    current_gpu = torch.cuda.device_count()
    print("Current device index: {}. Total number of devices: {}".format(current_gpu,num_gpus))
    torch.cuda.set_device(0)
    z = z.cuda()

    print("\nOn GPU: z = \n{}".format(z))
    print("Type ",z.type() ) # that's different to type(z) python does not know the difference

    print("Notice the type has now become torch.cuda.FloatTensor.")
    if num_gpus>=2:
        # Now let's send it to a different GPU if available
        print("Switching to a different device...")
        torch.cuda.set_device(1)
        print("Current device index: {}".format(torch.cuda.current_device()))
        z = z.cuda()
        print("On a different GPU: z = {}".format(z))
        print("Type ", z.type())
else:
    print("No GPU available")
# Send Tensor back to CPU
z = z.cpu()
print("\nOn CPU: z = {}".format(z))
print("Type ",z.type())

Current device index: 1. Total number of devices: 1

On GPU: z = 
tensor([2.], device='cuda:0')
Type  torch.cuda.FloatTensor
Notice the type has now become torch.cuda.FloatTensor.

On CPU: z = tensor([2.])
Type  torch.FloatTensor


Torch tensors can be coverted between numpy but only if theu are on **cpu**. First transfer to cpu then comvert to numpy.

In [25]:
# Convert Tensor to Numpy array and vice versa
import numpy as np
z = x + y
z = z.numpy()
print("Converted to numpy, z = {}\n{}".format(type(z), z))

z = torch.from_numpy(z)
print( "Converted to Tensor, z = {}".format(z))

# Note that the conversion is not possible when the Tensor is on GPU
z = z.cuda()
z = z.numpy()  # <<<< create error on purpose!!
#try:
#    z = z.numpy()
#except RuntimeError as e:
#    print( "Error: {}".format(e))

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### Timing
The speed improvement on GPU is subject of the next tutorial torch_tensor_tutorial_timing.ipynb